### ISSUE TITLE
Campaign can not be stored after creation due to a failed precondition "412"

### ISSUE THREAD

**Issue by mukil** [mukil/poemspace#1]
Maybe 
- here is missing a timestamp value in the header
- adding such is not opaque but we need to adapt our call of the dm4.restc 

`12.02.2016 20:36:06 de.deepamehta.core.util.UniversalExceptionMapper logException
SCHWERWIEGEND: Request "PUT /core/topic/5240" failed. Responding with 412 (Precondition Failed). The original exception/error is:
javax.ws.rs.WebApplicationException
    at de.deepamehta.plugins.caching.CachingPlugin.serviceRequestFilter(CachingPlugin.java:78)`

**Comment by jri** [comment]
Confirmed!
I can reproduce the 412 response.

In the original DM 4.1 based Poemspace installation this didn't happen as the "Edit Conflict Detection" feature is added only in DM 4.1.1

After a short investigation I found the PUT request is OK. The timestamp is there, that is in the `If-Unmodified-Since` header.

The problem is here: one of the various GET requests send while rendering the Mail Campaign form changes the modification timestamp of the Mail Campaign-Topic! At the moment I have no idea how this can happen. Further investigation is required.

Thank you very much for adapting to DM 4.7 and for reporting!

**Comment by mukil** [comment]
The latest fix makes editing a campaign in the webclient work again with an installed DeepaMehta 4 Caching module. There is no loss of data during subsequent edits of the "campaign" topic even if the display is affected  (indicating numbers next to criterias vanish on the left side in the edit form).

The underlying issue here is: the campaign topic form renderer does not utilize the dm4-core update mechanisms at all but is instead a fully customized AJAX form (creating & deleting associations to the campaign topic on the fly as checkboxes get selected). This is clearly not as intended by the dm4-webclient developers because the update logic (and data poemspace campaign data model) does not leverage the dm4-core. Consequently, the standard form processing should be supressed by our plugins custom page renderer and the "OK" button should not be rendered at all but replaced with a custom "OK" button rendered by our page renderer.

A look at the [lines 23-61](https://github.com/mukil/poemspace/blob/master/src/main/resources/migrations/migration2.json#L51) in the core type definition of a "Mail Campaign" tells more about how this plugin leverages dm4-core and manages contacts in relation to a campaign (as recipients).

**Comment by mukil** [comment]
The latest fix makes editing work in conjunction with an active dm4-caching module.
